trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '52.55.115.13:5985'
    UserName: 'EC2AMAZ-JBN5EJN\Administrator'
    UserPassword: ';r8HEqY-&inT55c*9tScRK=Tmv6avb!U'
    InlineScript: |
      # Write your powershell commands here.
      cd C:\Execution\ToscaExecutionClient\
      .\tosca_execution_client.ps1 -toscaServerUrl "http://localhost:80" -projectName "MultiUser_Workspace" -events '["TestEvent test"]'
    CommunicationProtocol: 'Http'