trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '172.31.92.95:5985'
    InlineScript: |
      # Write your powershell commands here.
      cd C:\Execution\ToscaExecutionClient\
      .\tosca_execution_client.ps1 -toscaServerUrl "http://localhost:80" -projectName "MultiUser_Workspace" -events '["TestEvent test"]'
      Write-Output "Hello World"
    CommunicationProtocol: 'Http'