trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Enter-PSSession -ComputerName 52.55.115.13 -Port 5985 -Credential EC2AMAZ-JBN5EJN\Administrator
      ;r8HEqY-&inT55c*9tScRK=Tmv6avb!U
      
